// Autogenerated by Thrift Compiler (0.12.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package main

import (
        "context"
        "flag"
        "fmt"
        "math"
        "net"
        "net/url"
        "os"
        "strconv"
        "strings"
        "github.com/apache/thrift/lib/go/thrift"
        "social_network"
)


func Usage() {
  fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
  flag.PrintDefaults()
  fmt.Fprintln(os.Stderr, "\nFunctions:")
  fmt.Fprintln(os.Stderr, "  void WriteUserTimeline(i64 req_id, i64 post_id, i64 user_id, i64 timestamp,  carrier)")
  fmt.Fprintln(os.Stderr, "   ReadUserTimeline(i64 req_id, i64 user_id, i32 start, i32 stop,  carrier)")
  fmt.Fprintln(os.Stderr)
  os.Exit(0)
}

type httpHeaders map[string]string

func (h httpHeaders) String() string {
  var m map[string]string = h
  return fmt.Sprintf("%s", m)
}

func (h httpHeaders) Set(value string) error {
  parts := strings.Split(value, ": ")
  if len(parts) != 2 {
    return fmt.Errorf("header should be of format 'Key: Value'")
  }
  h[parts[0]] = parts[1]
  return nil
}

func main() {
  flag.Usage = Usage
  var host string
  var port int
  var protocol string
  var urlString string
  var framed bool
  var useHttp bool
  headers := make(httpHeaders)
  var parsedUrl *url.URL
  var trans thrift.TTransport
  _ = strconv.Atoi
  _ = math.Abs
  flag.Usage = Usage
  flag.StringVar(&host, "h", "localhost", "Specify host and port")
  flag.IntVar(&port, "p", 9090, "Specify port")
  flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
  flag.StringVar(&urlString, "u", "", "Specify the url")
  flag.BoolVar(&framed, "framed", false, "Use framed transport")
  flag.BoolVar(&useHttp, "http", false, "Use http")
  flag.Var(headers, "H", "Headers to set on the http(s) request (e.g. -H \"Key: Value\")")
  flag.Parse()
  
  if len(urlString) > 0 {
    var err error
    parsedUrl, err = url.Parse(urlString)
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
    host = parsedUrl.Host
    useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http" || parsedUrl.Scheme == "https"
  } else if useHttp {
    _, err := url.Parse(fmt.Sprint("http://", host, ":", port))
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
  }
  
  cmd := flag.Arg(0)
  var err error
  if useHttp {
    trans, err = thrift.NewTHttpClient(parsedUrl.String())
    if len(headers) > 0 {
      httptrans := trans.(*thrift.THttpClient)
      for key, value := range headers {
        httptrans.SetHeader(key, value)
      }
    }
  } else {
    portStr := fmt.Sprint(port)
    if strings.Contains(host, ":") {
           host, portStr, err = net.SplitHostPort(host)
           if err != nil {
                   fmt.Fprintln(os.Stderr, "error with host:", err)
                   os.Exit(1)
           }
    }
    trans, err = thrift.NewTSocket(net.JoinHostPort(host, portStr))
    if err != nil {
      fmt.Fprintln(os.Stderr, "error resolving address:", err)
      os.Exit(1)
    }
    if framed {
      trans = thrift.NewTFramedTransport(trans)
    }
  }
  if err != nil {
    fmt.Fprintln(os.Stderr, "Error creating transport", err)
    os.Exit(1)
  }
  defer trans.Close()
  var protocolFactory thrift.TProtocolFactory
  switch protocol {
  case "compact":
    protocolFactory = thrift.NewTCompactProtocolFactory()
    break
  case "simplejson":
    protocolFactory = thrift.NewTSimpleJSONProtocolFactory()
    break
  case "json":
    protocolFactory = thrift.NewTJSONProtocolFactory()
    break
  case "binary", "":
    protocolFactory = thrift.NewTBinaryProtocolFactoryDefault()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
    Usage()
    os.Exit(1)
  }
  iprot := protocolFactory.GetProtocol(trans)
  oprot := protocolFactory.GetProtocol(trans)
  client := social_network.NewUserTimelineServiceClient(thrift.NewTStandardClient(iprot, oprot))
  if err := trans.Open(); err != nil {
    fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
    os.Exit(1)
  }
  
  switch cmd {
  case "WriteUserTimeline":
    if flag.NArg() - 1 != 5 {
      fmt.Fprintln(os.Stderr, "WriteUserTimeline requires 5 args")
      flag.Usage()
    }
    argvalue0, err244 := (strconv.ParseInt(flag.Arg(1), 10, 64))
    if err244 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    argvalue1, err245 := (strconv.ParseInt(flag.Arg(2), 10, 64))
    if err245 != nil {
      Usage()
      return
    }
    value1 := argvalue1
    argvalue2, err246 := (strconv.ParseInt(flag.Arg(3), 10, 64))
    if err246 != nil {
      Usage()
      return
    }
    value2 := argvalue2
    argvalue3, err247 := (strconv.ParseInt(flag.Arg(4), 10, 64))
    if err247 != nil {
      Usage()
      return
    }
    value3 := argvalue3
    arg248 := flag.Arg(5)
    mbTrans249 := thrift.NewTMemoryBufferLen(len(arg248))
    defer mbTrans249.Close()
    _, err250 := mbTrans249.WriteString(arg248)
    if err250 != nil { 
      Usage()
      return
    }
    factory251 := thrift.NewTJSONProtocolFactory()
    jsProt252 := factory251.GetProtocol(mbTrans249)
    containerStruct4 := social_network.NewUserTimelineServiceWriteUserTimelineArgs()
    err253 := containerStruct4.ReadField5(jsProt252)
    if err253 != nil {
      Usage()
      return
    }
    argvalue4 := containerStruct4.Carrier
    value4 := argvalue4
    fmt.Print(client.WriteUserTimeline(context.Background(), value0, value1, value2, value3, value4))
    fmt.Print("\n")
    break
  case "ReadUserTimeline":
    if flag.NArg() - 1 != 5 {
      fmt.Fprintln(os.Stderr, "ReadUserTimeline requires 5 args")
      flag.Usage()
    }
    argvalue0, err254 := (strconv.ParseInt(flag.Arg(1), 10, 64))
    if err254 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    argvalue1, err255 := (strconv.ParseInt(flag.Arg(2), 10, 64))
    if err255 != nil {
      Usage()
      return
    }
    value1 := argvalue1
    tmp2, err256 := (strconv.Atoi(flag.Arg(3)))
    if err256 != nil {
      Usage()
      return
    }
    argvalue2 := int32(tmp2)
    value2 := argvalue2
    tmp3, err257 := (strconv.Atoi(flag.Arg(4)))
    if err257 != nil {
      Usage()
      return
    }
    argvalue3 := int32(tmp3)
    value3 := argvalue3
    arg258 := flag.Arg(5)
    mbTrans259 := thrift.NewTMemoryBufferLen(len(arg258))
    defer mbTrans259.Close()
    _, err260 := mbTrans259.WriteString(arg258)
    if err260 != nil { 
      Usage()
      return
    }
    factory261 := thrift.NewTJSONProtocolFactory()
    jsProt262 := factory261.GetProtocol(mbTrans259)
    containerStruct4 := social_network.NewUserTimelineServiceReadUserTimelineArgs()
    err263 := containerStruct4.ReadField5(jsProt262)
    if err263 != nil {
      Usage()
      return
    }
    argvalue4 := containerStruct4.Carrier
    value4 := argvalue4
    fmt.Print(client.ReadUserTimeline(context.Background(), value0, value1, value2, value3, value4))
    fmt.Print("\n")
    break
  case "":
    Usage()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
  }
}
