# Start from the official Go image
FROM golang:1.22-alpine AS builder

# Set necessary environment variables
ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64

# Set the Current Working Directory inside the container
WORKDIR /app


# Install git for dependency downloads
RUN apk add --no-cache git

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Copy the source code from the current directory to the Working Directory inside the container
COPY . .

# Update go.mod and go.sum
RUN go mod tidy

# Build the Go app
RUN go build -o main .

# Start a new stage from scratch
FROM alpine:latest

# Set necessary environment variables
ENV GIN_MODE=release

# Install necessary packages
RUN apk --no-cache add ca-certificates

# Copy the Pre-built binary file from the previous stage
COPY --from=builder /app/main /app/main

# Expose port 8081 to the outside world
#EXPOSE 8081

# Command to run the executable
CMD ["/app/main"]